name: Build Extensions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build extensions
      run: ./gradlew :assembleRelease

    - name: Upload APKs
      uses: actions/upload-artifact@v3
      with:
        name: extension-apks
        path: "**/build/outputs/apk/**/*.apk"
